export const categories = [
    "Web Development",
    "App Development",
    "Programming Languages",
    "Data Science",
    "Machine Learning",
    "Artificial Intelligence",
    "Cyber Security",
    "Cloud Computing",
    "UI/UX Design",
    "Graphic Design",
    "Digital Marketing",
    "Business",
    "Finance",
    "Photography & Video",
    "Music",
    "Language Learning",
    "Personal Development",
];